### ISSUE TITLE
Zyne fails launch w python 2.7.15+, requires Python >= 2.6

### ISSUE THREAD

**Issue by mmmmna** [belangeo/zyne#4]
Ubuntu 18.04.2 up to date as of 2019 07 08.

Installed versions, from Ubuntu Bionic repositories:
Zyne 0.1.2-2

Python 2.7.15~rc1-1 (from Synaptic properties window), "2.7.15+" (as reported by console invocation of 'Python --version').

Error message from console when launching Zyne as user:

user@T5246-Ubuntu-Mate-18:~$ zyne
Traceback (most recent call last):
  File "/usr/bin/zyne", line 4, in <module>
    wxversion.select("2.8")
  File "/usr/lib/python2.7/dist-packages/wxversion.py", line 152, in select
    raise VersionError("Requested version of wxPython not found")
wxversion.VersionError: Requested version of wxPython not found
user@T5246-Ubuntu-Mate-18:~$

**Comment by belangeo** [comment]
You really should run Zyne from sources. This version is very old and the code is now based and developed with python 3 / wxPython 4. If pyo (`pip install pyo`), wxPython (there is pip packages for linux distros on wxpython.org ) and [pyotools](https://github.com/belangeo/pyo-tools) are nstalled, all you have to do is to clone zyne repo and:

```
cd zyne
python3 Zyne.py
```

**Comment by mmmmna** [comment]
All are more than I wish to perform.
